version: "2"
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - 5431:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
  app: 
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
