version: "2"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: imageit
      POSTGRES_DB: imageit

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
  app: 
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000